Add function for args, body args and query params in Action class
slimphp/Slim-Skeleton pull request #143
Opened 2019-12-11 14:07 UTC by Leezio

The array_key_exists() method allow to accepts the null value.

2020-12-25 22:08 UTC, idle-user commented
I did a similar thing with my project to resolve body args. But I would advise to keep `isset` as it is faster than `array_key_exists`.

Unless you're accepting null, then do a combination of both.

[Supporting comment](https://stackoverflow.com/posts/9522522/revisions)

2020-12-27 02:20 UTC, l0gicgate requested changes

2020-12-27 02:20 UTC, l0gicgate commented on src/Application/Actions/Action.php
> +        }
Can we remove the nested if/else and throw on the negative case instead and return otherwise? e.g.:

```php
if (!array_key_exists($name, $this->args)) {
    throw new HttpBadRequestException($this->request, "Could not resolve argument `" . $name . "`.");
}

return return $this->args[$name];
```

Let's do that for all the other methods introduced in this PR as well.

2021-03-22 00:30 UTC, l0gicgate commented
Stale

2021-03-22 00:30 UTC, closed without merging