add settings interface
slimphp/Slim-Skeleton pull request #206
Opened 2021-01-05 11:40 UTC by agungaprianto

add settings interface and mapping it with settings.php for easily access values on it

2021-01-06 02:11 UTC, l0gicgate requested changes

2021-01-06 02:11 UTC, l0gicgate commented on tests/Application/Actions/ActionTest.php
>              public function action() :Response
Instead of `$loggerInterface` and `$settingsInterface` it should just be `$logger` and `$settings`.

Also just noticed the spacing is wrong below:
```
public function action(): Response
```

2021-01-06 13:32 UTC, flangofas commented on src/Domain/Settings/Settings.php
> +
@agungaprianto please add `declare(strict_types=1);` at line 2 and avoid the double emplty lines

2021-01-06 13:32 UTC, flangofas commented on src/Domain/Settings/SettingsInterface.php
> +
@agungaprianto same as above

2021-01-06 16:01 UTC, agungaprianto commented on src/Domain/Settings/Settings.php
> +
thank's for the feedback, i've added in settings class and interface

2021-01-06 16:01 UTC, agungaprianto commented on tests/Application/Actions/ActionTest.php
>              public function action() :Response
i've changed wrong spacing that you requested.

2021-01-06 16:07 UTC, l0gicgate approved these changes

2021-01-07 09:52 UTC, flangofas commented on src/Domain/Settings/SettingsInterface.php
> +
@agungaprianto single line here as well.

2021-01-07 09:52 UTC, flangofas commented on src/Domain/Settings/Settings.php
> +
@agungaprianto single line here as well.

2021-01-07 09:54 UTC, flangofas approved these changes

2021-01-07 09:57 UTC, agungaprianto commented on src/Domain/Settings/SettingsInterface.php
> +
thank you for the feedback

2021-01-07 16:46 UTC, l0gicgate requested changes

2021-01-07 16:46 UTC, l0gicgate commented on src/Domain/Settings/Settings.php
> +    private $settings;
docbloc is missing.

2021-01-07 16:46 UTC, l0gicgate commented on src/Domain/Settings/Settings.php
> +    }
We should remove this setter and add a constructor which sets the property instead.

2021-01-07 16:46 UTC, l0gicgate commented on src/Domain/Settings/SettingsInterface.php
> +    public function set(array $settings): SettingsInterface;
this setter should be removed

2021-01-08 02:36 UTC, agungaprianto commented on src/Domain/Settings/Settings.php
> +    private $settings;
thank you for the feedback, i've updated some changes in this code

2021-01-08 05:34 UTC, l0gicgate requested changes

2021-01-08 05:34 UTC, l0gicgate commented on app/dependencies.php
> +        }
This definition should actually go in the `settings.php` file and we should replace the `settings` definition with this one instead.

2021-01-08 09:29 UTC, agungaprianto commented on app/dependencies.php
> +        }
```suggestion
return function (ContainerBuilder $containerBuilder) {
    // Global Settings Object
    $containerBuilder->addDefinitions([
        SettingsInterface::class => function () {
            $settings = [
                'displayErrorDetails' => true, // Should be set to false in production
                'logger' => [
                    'name' => 'slim-app',
                    'path' => isset($_ENV['docker']) ? 'php://stdout' : __DIR__ . '/../logs/app.log',
                    'level' => Logger::DEBUG,
                ],
            ];

            return new Settings($settings);
        },
    ]);
};
```

do you want to remove this definition and replace it the settings.php like this?

2021-01-08 17:19 UTC, l0gicgate requested changes

2021-01-08 17:19 UTC, l0gicgate commented on app/settings.php
> +        SettingsInterface::class => \DI\factory(function () {
You don't need a factory here. Just do:
```php
SettingsInterface::class => function (): SettingsInterface {
    // ...
},

2021-01-09 03:21 UTC, agungaprianto commented on app/settings.php
> +        SettingsInterface::class => \DI\factory(function () {
I've changed this code

2021-01-09 03:40 UTC, l0gicgate requested changes

2021-01-09 03:40 UTC, l0gicgate commented on src/Application/Actions/Action.php
> +    public function __construct(LoggerInterface $logger, SettingsInterface $settings)
What is the purpose of injecting the settings into the base action if it is not used anywhere?

2021-01-09 03:40 UTC, l0gicgate commented on src/Application/Actions/User/UserAction.php
> +use App\Application\Actions\Action as parentAlias;
Why do we need an alias?

2021-01-09 03:40 UTC, l0gicgate commented on src/Domain/Settings/SettingsInterface.php
> +namespace App\Domain\Settings;
Settings should be part of the Application aggregate, not the Domain aggregate. Let’s move them to the appropriate namespace.

2021-01-09 03:53 UTC, agungaprianto commented on src/Domain/Settings/SettingsInterface.php
> +namespace App\Domain\Settings;
why we need to change to the application aggregate? i mean why settings can be part of Application aggregate not Domain it self?

2021-01-09 03:55 UTC, agungaprianto commented on src/Application/Actions/User/UserAction.php
> +use App\Application\Actions\Action as parentAlias;
ah, maybe i'm doing something with my ide and doesn't aware of this. i'll remove it

2021-01-09 03:57 UTC, agungaprianto commented on src/Application/Actions/Action.php
> +    public function __construct(LoggerInterface $logger, SettingsInterface $settings)
i think if i injected settings in the base action it can be easily to get setting value for everything class , just call it 
`
$this->settings->get('key')
`

2021-01-09 04:19 UTC, l0gicgate commented on src/Domain/Settings/SettingsInterface.php
> +namespace App\Domain\Settings;
Because it has nothing to do with the Domain layer. The settings in question are at related to the application itself.

2021-01-09 04:20 UTC, l0gicgate commented on src/Application/Actions/Action.php
> +    public function __construct(LoggerInterface $logger, SettingsInterface $settings)
It’s unnecessary though, the logger shouldn’t actually even be in the base action. I initially put it there just as an example of dependency injection into an action.

2021-01-09 04:22 UTC, agungaprianto commented on src/Domain/Settings/SettingsInterface.php
> +namespace App\Domain\Settings;
ok. i'll move it

2021-01-09 04:36 UTC, l0gicgate approved these changes
Thank you for your contribution!

2021-01-09 04:36 UTC, merged

2021-01-09 04:37 UTC, agungaprianto commented on src/Application/Actions/Action.php
> +    public function __construct(LoggerInterface $logger, SettingsInterface $settings)
i think the way you put UserRepository in UserAction's constructor it's enough to give an example of dependency injection.