Allow PHP 8 usage
slimphp/Slim-Skeleton pull request #218
Opened 2021-03-11 19:28 UTC by jamesrweb

Currently when installing via composer on a PHP 8 machine, this throws an error due to the PHP 7 requirement currently in place.

2021-03-21 17:05 UTC, isalcedo commented
This seems right.

2021-03-22 00:20 UTC, l0gicgate commented
`phpunit/phpunit:8.5` is not compatible with PHP 8.0, need to add `8.5|9.5` to the dependency for this to work

2021-03-22 00:20 UTC, l0gicgate requested changes
phpunit/phpunit:8.5 is not compatible with PHP 8.0, need to add 8.5|9.5 to the dependency for this to work

2021-03-22 01:03 UTC, jamesrweb commented
> phpunit/phpunit:8.5 is not compatible with PHP 8.0, need to add 8.5|9.5 to the dependency for this to work

Like that?

2021-04-25 07:30 UTC, David-Baron commented
the command:

```bash
 composer create-project slim/slim-skeleton:dev-master .
```
result: 

```bach
[InvalidArgumentException]
Could not find package slim/slim-skeleton with version dev-master in a version installable using your PHP version, PHP extensions and Composer version.
```
The command:

```bash
 composer create-project slim/slim-skeleton:dev-master . ^4.*
```
result:

```bash
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Root composer.json requires slim/psr7 ^0.5 -> satisfiable by slim/psr7[0.5.0].
    - slim/psr7 0.5.0 requires php ^7.1 -> your php version (8.0.3) does not satisfy that requirement.
  Problem 2
    - phpunit/phpunit[7.5.0, ..., 7.5.20] require php ^7.1 -> your php version (8.0.3) does not satisfy that requirement.
    - Root composer.json requires phpunit/phpunit ^7.5 -> satisfiable by phpunit/phpunit[7.5.0, ..., 7.5.20].
```

2021-04-25 07:56 UTC, David-Baron commented
The slim/psr7 v1.3.0 is autoinstalled with slim/slim so why is in composer.json?
and the phputit with php 8.0 version is 9.5. need to be instaled manualy

2021-04-25 08:07 UTC, David-Baron commented
To install with php8:
- download the skeleton archive
- install vendor with: composer install --ignore-platform-reqs

2021-04-26 02:48 UTC, l0gicgate approved these changes

2021-04-26 02:48 UTC, merged

2021-04-26 03:04 UTC, l0gicgate commented
Here is the release:
https://github.com/slimphp/Slim-Skeleton/releases/tag/4.3.0